baseurl = "http://onecampus.github.io/"
languageCode = "zh-CN"
title = "Onecampus T.D."
theme = "hyde"

[params]
	description = "I am the bone of my sword."
	#disqusShortname = "spf13"

[[menu.footer]]
	Name = "Organization"
	Url = "https://github.com/onecampus"
	